"""add warnings column to tasks

Revision ID: b1bdaf76715f
Revises: f1fa1ed67ec5
Create Date: 2026-06-13 15:44:11.001939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1bdaf76715f'
down_revision: Union[str, Sequence[str], None] = 'f1fa1ed67ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('warnings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'warnings')
    # ### end Alembic commands ###
